[package]
name = "hello_world"
version = "0.1.0"
authors = ["Alex-Lu-hub <2326521374@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"